# Generated by Django 3.2.4 on 2021-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
