# Generated by Django 3.2.4 on 2021-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
