# Generated by Django 3.2.4 on 2021-07-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_users_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField()),
                ('des', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
    ]
