# Generated by Django 3.2.4 on 2021-07-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='/media/default-profile-picture.jpg', upload_to='pics'),
        ),
    ]
