# Generated by Django 3.2.4 on 2021-07-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='/media/default-profile-picture.jpg', upload_to='img/%y'),
        ),
    ]
