# Generated by Django 3.2.4 on 2021-07-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_username', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
    ]
